---
- name: Install ops-tool
  become_user: "{{ user.name }}"
  unarchive:
    src: https://github.com/itmecho/ops-tool/releases/download/0.1.0/ops-tool-x86_64-unknown-linux-gnu.tgz
    dest: "{{ user.home }}/bin"
    mode: 0700
    remote_src: true
