---
- name: Configure GPG agent
  become: true
  become_user: "{{ user.name }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: gpg-agent.conf,  dest: "{{ user.home }}/.gnupg/gpg-agent.conf" }
    - { src: pam_environment, dest: "{{ user.home }}/.pam_environment"      }
