---
- name: Initialisation
  hosts: all
  roles:
    - sudo
    - pacman
    - user
  tasks:
    - name: Clone ansible-aur-git
      become_user: "{{ user.name }}"
      git:
        repo: https://aur.archlinux.org/ansible-aur-git.git
        dest: /tmp/ansible-aur-git

    - name: Install ansible-aur-git
      become_user: "{{ user.name }}"
      command:
        cmd: makepkg -si
        chdir: /tmp/ansible-aur-git

  vars_prompt:
    - name: username
      prompt: Enter the username for the new user
      private: false

    - name: password
      prompt: Enter the password for the new user
