#!/bin/sh

set -e

if [ $(id -u) -ne 0 ]; then
    echo "ERROR: must be run as root"
    exit 1
fi

echo ":: installaing dependencies"
pacman -S --needed --noconfirm base-devel git ansible

playbook=$1
echo ":: running playbook for $playbook"
ansible-playbook -i inventory --extra-vars "@vars/${playbook}.yaml" init.yaml
ansible-playbook -i inventory --extra-vars "@vars/${playbook}.yaml" playbook.yaml
