#!/bin/sh

set -e

if [ $(id -u) -ne 0 ]; then
    echo "ERROR: must be run as root"
    exit 1
fi

echo ":: installing dependencies"
pacman -S --needed --noconfirm base-devel git ansible

playbook=$1
echo ":: running playbook for $playbook"
echo -n "Enter username for the new user: "
read username
ansible-playbook -i inventory --extra-vars "username=${username}" --extra-vars "@vars/${playbook}.yaml" init.yaml
ansible-playbook -i inventory --extra-vars "username=${username}" --extra-vars "@vars/${playbook}.yaml" playbook.yaml
