---
- name: Install bspwm and dependencies
  pacman:
    name:
      - bspwm
      - i3lock-color
      - xautolock
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
    state: present

- name: User space tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Install bsp-layout
      aur:
        name: bsp-layout
        use: yay
        extra_args:
          - "--needed"

    - name: Create config directory
      file:
        path: "{{ user.home }}/.config/bspwm"
        state: directory

    - name: Configure bspwm
      template:
        src: bspwmrc
        dest: "{{ user.home }}/.config/bspwm/bspwmrc"
        mode: 0700

    - name: Copy lockscreen script
      copy:
        src: lock.sh
        dest: "{{ user.home }}/.config/bspwm/lock.sh"
        mode: 0700

    - name: Copy xinit script
      template:
        src: xinitrc
        dest: "{{ user.home }}/.xinitrc"
