---
- name: Install zsh
  pacman:
    name: zsh
    state: present

- name: Install and configure oh-my-zsh
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Check if oh-my-zsh is installed
      stat:
        path: "{{ user.home }}/.oh-my-zsh"
      register: check

    - name: Install tasks
      when: not check.stat.exists
      block:
        - name: Download installer
          get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: /tmp/omz.sh
            mode: 0755

        - name: Run installer
          command:
            cmd: /tmp/omz.sh
            creates: "{{ user.home }}/.oh-my-zsh"

        - name: Remove installer
          file:
            path: /tmp/omz.sh
            state: absent

    - name: Configure zsh
      template:
        src: zshrc
        dest: "{{ user.home }}/.zshrc"

    - name: Install zsh plugins
      git:
        repo: https://github.com/zsh-users/{{ item }}
        dest: "{{ user.home }}/.oh-my-zsh/custom/plugins/{{ item }}"
        clone: true
      loop:
        - zsh-autosuggestions
        - zsh-syntax-highlighting
