---
- name: Install and configure polybar
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Install polybar
      aur:
        name: polybar
        use: yay
        extra_args:
          - "--needed"

    - name: Create config directory
      file:
        path: "{{ user.home }}/.config/polybar"
        state: directory

    - name: Copy configuration
      template:
        src: config
        dest: "{{ user.home }}/.config/polybar/config"

    - name: Copy scripts
      copy:
        src: "{{ item }}"
        dest: "{{ user.home }}/.config/polybar/{{ item }}"
        mode: 0700
      loop:
        - checkupdates.sh
        - listupdates.sh

    - name: Copy work scripts
      when: is_work | default(false)
      copy:
        src: "{{ item }}"
        dest: "{{ user.home }}/.config/polybar/{{ item }}"
        mode: 0700
      loop:
        - grafana_alerts.sh
        - grafana_alerts_list.sh
        - vpn.sh

- name: Create hooks directory
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Install pacman hook
  copy:
    src: polybar-updates.hook
    dest: /etc/pacman.d/hooks/polybar-updates.hook
    mode: 0644
