---
- name: Install nvidia drivers
  when: graphics == 'nvidia'
  block:
    - name: Install 64-bit drivers
      pacman:
        name:
          - nvidia
          - nvidia-utils
          - vulkan-icd-loader
        state: present

    - name: Install 32-bit drivers
      when: enable_multilib | default(false)
      pacman:
        name:
          - lib32-nvidia-utils
          - lib32-vulkan-icd-loader
        state: present

- name: Install AMD drivers
  when: graphics == 'radeon'
  block:
    - name: Install 64-bit drivers
      pacman:
        name:
          - mesa
          - vulkan-radeon
          - vulkan-icd-loader
        state: present

    - name: Install 32-bit drivers
      when: enable_multilib | default(false)
      pacman:
        name:
          - lib32-mesa
          - lib32-vulkan-mesa
          - lib32-vulkan-icd-loader

