---
- name: Install rofi
  pacman:
    name: rofi
    state: present

- name: Userspace tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Create config directory
      file:
        path: "{{ user.home }}/.config/rofi"
        state: directory

    - name: Configure rofi
      become_user: "{{ user.name }}"
      copy:
        src: "{{ item }}"
        dest: "{{ user.home }}/.config/rofi/{{ item }}"
      loop:
        - config.rasi
        - gruvbox-common.rasi
        - gruvbox-dark.rasi
