---
- name: Install rofi
  pacman:
    name: rofi
    state: present

- name: Userspace tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Create config directory
      file:
        path: "{{ user.home }}/.config/rofi"
        state: directory

    - name: Copy configuration
      copy:
        src: "{{ item }}"
        dest: "{{ user.home }}/.config/rofi/{{ item }}"
      loop:
        - config.rasi
        - nord.rasi
        - powermenu.rasi

    - name: Add rofi scripts
      copy:
        src: "{{ item }}"
        dest: "{{ user.home }}/.config/rofi/{{ item }}"
        mode: 0755
      loop:
        - powermenu.sh
