---
- name: Install packages
  pacman:
    name:
      - mopidy
      - mpc
      - ncmpcpp

- name: User tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Install plugins
      aur:
        name:
          - mopidy-mpd
          - mopidy-spotify
        use: yay

    - name: Create configuration directory
      file:
        path: "{{ user.home }}/.config/mopidy"
        state: directory

    - name: Configure mopidy
      template:
        src: mopidy.conf
        dest: "{{ user.home }}/.config/mopidy/mopidy.conf"
