---
- name: Install alacritty
  pacman:
    name:
      - alacritty
      - ttf-jetbrains-mono
    state: present

- name: Userspace tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Install mononoki font
      aur:
        name: nerd-fonts-mononoki
        skip_installed: true
        use: yay
    - name: Create config directory
      file:
        path: "{{ user.home }}/.config/alacritty"
        state: directory

    - name: Configure alacritty
      template:
        src: alacritty.yml
        dest: "{{ user.home }}/.config/alacritty/alacritty.yml"
