---
- name: Install alacritty
  pacman:
    name: alacritty
    state: present

- name: Configure alacritty
  copy:
    src: alacritty.yml
    dest: "{{ user.home }}/.config/alacritty/alacritty.yml"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
