---
- name: Install neovim
  pacman:
    name:
      - neovim
      - python-pynvim
      # dependencies for coc.nvim
      - nodejs
      - yarn
    state: present

- name: Link vim to nvim system wide
  file:
    path: /usr/bin/vim
    src: /usr/bin/nvim
    state: link

- name: Set theme name
  set_fact:
    theme_name: "{{ 'dracula' if theme is defined and theme == 'dracula' else 'gruvbox' }}"

- name: Run userspace tasks
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Create configuration directory
      file:
        path: "{{ user.home }}/.config/nvim"
        state: directory

    - name: Configure neovim
      template:
        src: init.vim
        dest: "{{ user.home }}/.config/nvim/init.vim"

    - name: Create include directory
      file:
        path: "{{ user.home }}/.config/nvim/include"
        state: directory

    - name: Copy RNR
      copy:
        src: rnr.vim
        dest: "{{ user.home }}/.config/nvim/include/rnr.vim"

    - name: Create nvim autoload directory
      file:
        path: "{{ user.home }}/.local/share/nvim/site/autoload"
        state: directory

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ user.home }}/.local/share/nvim/site/autoload/plug.vim"

    - name: Install plugins
      command: nvim +PlugInstall +qa
