---
- name: Install neovim
  pacman:
    name:
      - neovim
      - python-pynvim
    state: present

- name: Link vim to nvim system wide
  file:
    path: /usr/bin/vim
    src: /usr/bin/nvim
    state: link

- name: Run userspace tasks
  become_user: "{{ user.name }}"
  block:
    - name: Configure neovim
      copy:
        src: init.vim
        dest: "{{ user.home }}/.config/nvim/init.vim"

    - name: Create nvim autoload directory
      file:
        path: "{{ user.home }}/.local/share/nvim/site/autoload"
        state: directory

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ user.home }}/.local/share/nvim/site/autoload/plug.vim"

    - name: Install plugins
      command: nvim +PlugInstall +qa
